### ISSUE TITLE
Tensorflow and Sonnet versions 2.0 doesn't work

### ISSUE THREAD

**Issue by NagabhushanSN95** [deepmind/kinetics-i3d#85]
Hi,
To install Sonnet, you redirect to [Sonnet Pape](https://github.com/deepmind/sonnet).
But now, that page refers to install tf and sonnet 2.0. Those versions are not compatible with I3D. We get the below error

```
Traceback (most recent call last):
  File "evaluate_sample.py", line 24, in <module>
    import i3d
  File "/media/nagabhushan/Data02/SNB/IISc/Research/01_Video_Generator/Workspace/Metrics/Research/002_Feature_Space_NeuralNetworks/code/kinetics-i3d/i3d.py", line 32, in <module>
    class Unit3D(snt.AbstractModule):
AttributeError: module 'sonnet' has no attribute 'AbstractModule'
```

This can be resolved by using tensorflow and sonnet 1.* versions as specified [here](https://github.com/deepmind/kinetics-i3d/issues/67)

So, can you please put a requirements.txt file so that future users can easily pick from that?

**Comment by pengxuding** [comment]
two methods:
1. pip uninstall de-sonnet, then pip install sonnet
2. pip install --upgrade tensorflow-gpu
you can try
