### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.distribute' has no attribute 'experimental'

### ISSUE THREAD

**Issue by tempdeltavalue** [deepmind/kinetics-i3d#91]
:~/Desktop/I3D/kinetics-i3d$ python3 i3d_test.py

Traceback (most recent call last):
  File "i3d_test.py", line 24, in <module>
    import i3d
  File "/home/nazariy/Desktop/I3D/kinetics-i3d/i3d.py", line 28, in <module>
    import sonnet as snt
  File "/home/nazariy/.virtualenvs/pixellot-ml-py3/lib/python3.6/site-packages/sonnet/__init__.py", line 22, in <module>
    from sonnet import distribute
  File "/home/nazariy/.virtualenvs/pixellot-ml-py3/lib/python3.6/site-packages/sonnet/distribute.py", line 22, in <module>
    from sonnet.src.replicator import Replicator
  File "/home/nazariy/.virtualenvs/pixellot-ml-py3/lib/python3.6/site-packages/sonnet/src/replicator.py", line 95, in <module>
    class TpuReplicator(tf.distribute.experimental.TPUStrategy):
AttributeError: module 'tensorflow._api.v1.distribute' has no attribute 'experimental'

tensorflow-estimator  1.13.0     
tensorflow-gpu        1.13.1  
dm-sonnet             2.0.0b0

**Comment by AlexanderMelde** [comment]
try using sonnet version 1, see https://github.com/deepmind/kinetics-i3d/issues/85
